language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: mkjez6h92BdwBtvQU0KAj1Oa0so4uquR4/Xo+DGNHFYE+FlyAZ4SqaUnbakEBwD2fnSP8FE69NvxERJa8lHF/nmex7CpGQxpYLiSl2JfvgLAxFl8ivmdnHcmrVOm34g7n4Sxr8bjBH4xXD4Dl24Co5X3wpSlKPzLvcnNW13wYt6dAjxNewzB5qkbU3I5igV4RL/+rQRmT7nBtHQV6/gf8t5Ol12T+EJnf0zhnMIYcpaJcUw3nCXsARaupKKeWcHdp4xyW5ic/k6/5LIOrOhEjxInNDkRybTi0OCs/iYHaf6gHujAw8XDM5nxEf5MDd9qur2Mu8yZ/sc51TqlwtLHrCkrG2PwRkwlNaWUkIIDVxmebVh2G94TmWN0dDcIeiid/4Mk8Bz/jbdwmEk7JBO5v/mH/v+CTIMwaBw0ed3BtUWfsXJ/VOVrEH2+g/YT63eUMd7nxXqXMSaSVd3ygLShjj5x6FdVr9/rDaA1lTUT1CQYPuXRixoNLhsqNJMsKNXP2ovVFHhry/SLQTZmgx663IZwTuROLy0Spf6c/P+3HS6OfZkn7wvA4D1H0AMFDJ4qRDquJ1F+IsViQooIHoUH2foBzVvDa8kMgNKt8nqfcmDUeWqFE/7I7FfRG9LvGo5hgVj6H2uSQgwZ0u5lAuDrB/peqV/EJbjR5ntzWlLlJMk=
